# CodeClimate Code Check configuration
# https://codeclimate.com/github/VevoxDigital/Skribki

engines:
  duplication:
    enabled: true
    exclude_paths:
    - test/ # Please stop looking for duplicates in tests
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - 'src/app/**'
  - 'hooks/**'
